name: Lootpool update

on:
  push:
    paths:
      - 'modifier/lootpool_default.py'

jobs:
  run_lootpool_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run lootpool.py
      run: python modifier/lootpool.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update from lootpool.py" || echo "No changes to commit"
        git push
